title: "Abdulkadir’s Essays"
description: "Linguistic researcher and language teacher"
theme: minima
collections:
  essays:
    output: true
    permalink: /essays/:name/
  academic:
    output: true
    permalink: /academic/:name/

defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "academic"
    values:
      layout: "post"


# optional: plugins: [jekyll-feed]
