# Site settings
title: "Abdulkadir Şenel"
description: "Linguistic researcher and language teacher"
collections:
  academic:
    output: true
  essays:
    output: true
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap


