

# Site settings
title: "Abdulkadir Şenel"
description: "Linguistic researcher and language teacher"
baseurl: ""
url: ""

# Collections
collections:
  essays:
    output: true
    permalink: /essays/:name/
  academic:
    output: true
    permalink: /academic/:name/

# Default settings for collections
defaults:
  - scope:
      path: ""
      type: "essays"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "academic"
    values:
      layout: "post"

# Build settings
markdown: kramdown
highlighter: rouge

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# optional: plugins: [jekyll-feed]
