title: "Abdulkadir’s Essays"
description: "Linguistic researcher and language teacher"
theme: minima
collections:
  academic:
    output: true
  essays:
    output: true
    permalink: /essays/:path/

# optional: plugins: [jekyll-feed]
