title: "Abdulkadir’s Essays"
description: "Linguistic researcher and language teacher"
theme: minima
collections:
  academic:
    output: true
  essays:
    output: true
permalink: /:collection/:name/
# optional: plugins: [jekyll-feed]
